###Get service document-contains the entity sets of the entire service.
http://localhost:4004/odata/v4/MyService
###Get service metadata
http://localhost:4004/odata/v4/MyService/$metadata

###Get all the employee data in JSON
DELETE http://localhost:4004/odata/v4/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C19787FB

###
POST http://localhost:4004/odata/v4/CatalogService/POs
Content-Type: application/json

{
     "nameFirst": "Harsh",
      "nameMiddle": null,
      "nameLast": "Joshi",
      "nameInitials": null,
      "sex": "F",
      "language": "E",
      "phoneNumber": null,
      "email":"paul.c@example.com",
      "loginName": "SUMHARRS",
      "Currency_code": "USD",
      "salaryAmount": 1009,
      "accountNumber": "9182776655",
      "bankId": "304000158",
      "bankName": "My Bank of San Francisco"
}

###
 http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC28052
